[build]
  publish = "public"
  functions = "functions"
  # command = "npm run build"  # Uncomment if you have a build step

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
