[build]
  publish = "public"
  functions = "functions"
  command = "npm run build"  # (optional) if you have a build step; otherwise, you can remove this line

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
[build]
  publish = "public"
  functions = "functions"
  command = "npm run build"  # (optional) if you have a build step; otherwise, you can remove this line

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
